// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZYDgm13cRBUe8Jw0etx294Ti4aqyL6hg',
    appId: '1:498052726577:web:c07e55b9047f338220ba10',
    messagingSenderId: '498052726577',
    projectId: 'ecommerceapp-9e9ba',
    authDomain: 'ecommerceapp-9e9ba.firebaseapp.com',
    storageBucket: 'ecommerceapp-9e9ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEt3xOd_1p_2K6TRNjhAe6f6RiHGXEq64',
    appId: '1:498052726577:android:00c71e5bff148b5020ba10',
    messagingSenderId: '498052726577',
    projectId: 'ecommerceapp-9e9ba',
    storageBucket: 'ecommerceapp-9e9ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4NIAMIh5pryX4sTOiXYTpF7wgew3ptpI',
    appId: '1:498052726577:ios:9191732d757e71ef20ba10',
    messagingSenderId: '498052726577',
    projectId: 'ecommerceapp-9e9ba',
    storageBucket: 'ecommerceapp-9e9ba.appspot.com',
    androidClientId: '498052726577-ofcgmkspu3k7fv56o9t246dfoe26oqbt.apps.googleusercontent.com',
    iosClientId: '498052726577-re47tcibc0vsm2lsc62nkg3bqvoc8haq.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );
}
